# Generated by Django 4.2.2 on 2023-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_alter_address_options_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='published_books',
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
